[workspace]
members = ["b0", "backend/cc", "backend/yul"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
pest = "2.7"
pest_derive = "2.7"

anyhow = "1.0"
tokio = { version = "1.41" }

vacan-b0 = { path = "b0" }
