test_function(arg1: U8, arg2: U8) U8 {
    // Declare variable and assign with type.
	a :u8 = 1;
	// Declare variable and assign.
	a := b;

    // Function Call
    call_func(1, a);

	// Assign value
	a = 1;

    // Assign function call
    a = call(a, 1, 2);

    // Assign string
    a = "";

    // Assign int
    a = 1;

    // Assign float
    a = 1.1;

    // Assign hex
    a = 0xabcd;

    // If Statement
    func(a, b) {
        // Some Statements Here
    } func(a, b) {
        // Some Statements Here
    } func(a, b) {
        // Some Statements Here
    }

    // For Statement
    (a:= 1; func(a, b); incr(a)) {
        // Statements
    }

    // Return
    <= 1;
}