@dec(1, 1, 3)
test_function(arg1: U8, arg2: U8) U8 {
    // Declare variable and assign with type.
	a :u8 = 1;

    // Function Call
    call_func(1, a);

    // Assign function call
    a = call(a, 1, 2);

    
    // For Statement
    (a:= 1; ; incr(a)) {
        // Statements
        <= 1;
    }

    // If Statement
    func(a, b) {
        // Some Statements Here
        a = 0xabcd;
    } func(a, b) {
        // Some Statements Here
        a = 0xabcd;
    } func(a, b) {
        // Some Statements Here
        a = 0xabcd;
    }

    <= 1;
}
